# Generated by Django 4.2.1 on 2023-05-16 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaboration_app', '0004_remove_task_duration_task_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='code',
            field=models.CharField(help_text='eg.ZATY123D', max_length=8, unique=True),
        ),
        migrations.AlterModelTable(
            name='group',
            table='group',
        ),
        migrations.AlterModelTable(
            name='groupmessage',
            table='group_message',
        ),
        migrations.AlterModelTable(
            name='task',
            table='task',
        ),
        migrations.AlterModelTable(
            name='taskmessage',
            table='task_message',
        ),
    ]
