# Generated by Django 4.2.1 on 2023-05-29 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaboration_app', '0005_alter_group_code_alter_group_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='code',
            field=models.CharField(help_text='Please enter a group code to join eg, ZATY123D', max_length=8, unique=True),
        ),
    ]
