# Generated by Django 4.2.1 on 2023-05-31 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaboration_app', '0007_alter_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(upload_to=''),
        ),
    ]
