# Generated by Django 4.2.1 on 2023-05-31 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collaboration_app', '0008_alter_customuser_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='avatar',
        ),
    ]
