# Generated by Django 4.2.1 on 2023-05-31 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaboration_app', '0009_remove_customuser_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(default='user.png', upload_to=''),
        ),
    ]
