# Generated by Django 4.2.1 on 2023-06-09 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaboration_app', '0012_rename_task_members_task_assign_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmessage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
