# Generated by Django 4.2.1 on 2023-07-17 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collaboration_app', '0014_messagereply'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='group_type',
            field=models.CharField(choices=[('public', 'public'), ('private', 'private')], default='private', max_length=10),
        ),
        migrations.AlterField(
            model_name='messagereply',
            name='group_message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='collaboration_app.groupmessage'),
        ),
    ]
