# Generated by Django 4.2.1 on 2023-07-22 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaboration_app', '0016_task_files_submitted_task_number_of_files_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='task_file',
        ),
        migrations.AddField(
            model_name='task',
            name='name',
            field=models.FileField(blank=True, upload_to='files'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(help_text='Enter the detail of the task in stepwise'),
        ),
        migrations.DeleteModel(
            name='TaskMessage',
        ),
    ]
