# Generated by Django 4.2.1 on 2023-07-22 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaboration_app', '0018_remove_task_name_task_task_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_file',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
