# Generated by Django 4.2.1 on 2023-07-23 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collaboration_app', '0019_alter_task_task_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='task_file',
        ),
        migrations.CreateModel(
            name='TaskFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_file', models.FileField(upload_to='task_files/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collaboration_app.task')),
            ],
            options={
                'db_table': 'task_file',
            },
        ),
    ]
