# Generated by Django 4.2.1 on 2023-07-23 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collaboration_app', '0020_remove_task_task_file_taskfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskfile',
            name='file_extension',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='taskfile',
            name='file_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='taskfile',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='collaboration_app.task'),
        ),
    ]
